### ISSUE TITLE
Missing Taglibs in deliveryManagment.jsp

### ISSUE THREAD

**Issue by hxshan** [Sithumpramu/EclipseTest#2]
Add the following tags and see
``` <%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>```
 ```<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %>```

If it does not work try just displaying the session variable with ```<p>${orderss}</p>```  if there is nothing still
then see whether the servlet sets the session variable before it redirects to the jsp

**Comment by Sithumpramu** [comment]
Missing Tags is the case. Now working properly.
